{
 "title": "OpenWrt",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "type_instance",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM \"iptables_value\" WITH KEY=type_instance"
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": "SHOW TAG VALUES FROM \"interface_rx\" WITH KEY=instance"
   },
   {
    "name": "wifi_if",
    "label": "Wi-Fi Interface",
    "query": "SHOW TAG VALUES FROM \"iwinfo_value\" WITH KEY=instance "
   },
   { "name": "ip_family", "label": "IP Family", "query": "show measurements" }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "cpu$tag_instance $tag_type_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "query": "SELECT mean(\"value\") FROM \"cpu_value\" WHERE $timeFilter GROUP BY time($__interval), \"host\", \"instance\", \"type_instance\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "1m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load_shortterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "5m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load_midterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "15m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load_longterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_type_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "rx_$tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface_rx",
     "query": "SELECT 8 * non_negative_derivative(mean(\"value\"), 1s) FROM \"interface_rx\" WHERE (\"type\" =~ /if_(octets)/ AND \"instance\" =~ /^$interface$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"instance\", \"type\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=~", "value": "/if_(octets)/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$interface$/" }
     ]
    },
    {
     "alias": "tx_$tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "interface_tx",
     "query": "SELECT 8 * non_negative_derivative(mean(\"value\"), 1s) FROM \"interface_tx\" WHERE (\"type\" =~ /if_(octets)/ AND \"instance\" =~ /^$interface$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"instance\", \"type\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=~", "value": "/if_(octets)/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$interface$/" }
     ]
    }
   ]
  },
  {
   "title": "TX Total",
   "type": "table",
   "gridPos": { "h": 9, "w": 3, "x": 18, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "($__to-$__from)s" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "interface_rx",
     "query": "SELECT max(value)-min(value) FROM interface_tx WHERE type='if_octets' AND $timeFilter GROUP BY instance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$interface$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_octets" }
     ]
    }
   ]
  },
  {
   "title": "RX Total",
   "type": "table",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "($__to-$__from)s" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "interface_rx",
     "query": "SELECT max(value)-min(value) FROM interface_rx WHERE type='if_octets' AND $timeFilter GROUP BY instance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$interface$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_octets" }
     ]
    }
   ]
  },
  {
   "title": "LAN TX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_type_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" }
     ],
     "measurement": "iptables_value",
     "query": "SELECT 8 * non_negative_derivative(mean(\"value\"), 1s) FROM $ip_family WHERE (\"type\" = 'ipt_bytes' AND \"instance\" = 'mangle-iptmon_tx' AND \"type_instance\" =~ /tx_$type_instance/) AND $timeFilter GROUP BY time($__interval), type_instance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "ipt_bytes" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "mangle-iptmon_tx" }
     ]
    }
   ]
  },
  {
   "title": "LAN TX Totals",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 18 },
   "targets": [
    {
     "alias": "$tag_type_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iptables_value",
     "query": "SELECT max(\"value\")-min(\"value\") FROM $ip_family WHERE (\"type\" = 'ipt_bytes' AND instance = 'mangle-iptmon_tx' AND \"type_instance\" =~ /tx_$type_instance/ ) AND $timeFilter GROUP BY \"type_instance\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "ipt_bytes" }
     ]
    }
   ]
  },
  {
   "title": "LAN RX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_type_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" }
     ],
     "measurement": "iptables_value",
     "query": "SELECT 8 * non_negative_derivative(mean(\"value\"), 1s) FROM $ip_family WHERE (\"type\" = 'ipt_bytes' AND \"instance\" = 'mangle-iptmon_rx' AND \"type_instance\" =~ /rx_$type_instance/) AND $timeFilter GROUP BY time($__interval), type_instance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "ipt_bytes" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "mangle-iptmon_rx" }
     ]
    }
   ]
  },
  {
   "title": "LAN RX Totals",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 27 },
   "targets": [
    {
     "alias": "$tag_type_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iptables_value",
     "query": "SELECT max(\"value\")-min(\"value\") FROM $ip_family WHERE (\"type\" = 'ipt_bytes' AND instance = 'mangle-iptmon_rx' AND \"type_instance\" =~ /rx_$type_instance/ ) AND $timeFilter GROUP BY \"type_instance\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "ipt_bytes" }
     ]
    }
   ]
  },
  {
   "title": "Wi-Fi Signal Quality",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "alias": "$tag_instance $tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iwinfo_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=~", "value": "/^(signal.*)/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$wifi_if$/" }
     ]
    }
   ]
  },
  {
   "title": "Wi-Fi Clients",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 36 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iwinfo_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "stations" }
     ]
    }
   ]
  },
  {
   "title": "DNS requests/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_type_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dns_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temp",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 40 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "thermal_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}